### ISSUE TITLE
`django-model-utils` 2.4 removes `PassThroughManagerMixin`.

### ISSUE THREAD

**Issue by mrmachine** [jp74/django-model-publisher#24]
Django 1.7 has `as_manager()` now which does the same thing as `PassThroughManager`. For `PassThroughManagerMixin`, I think people can use `PublisherManager.from_queryset(...)()` instead.

Alternatively, you will need to pin to `django-model-utils<2.4`, which doesn't have Django 1.9 compatibility.

**Comment by mrmachine** [comment]
Should be fixed by #26

**Comment by leesolway** [comment]
Looks good, thankyou. Please could you make sure tests are passing.

**Comment by mrmachine** [comment]
I had some trouble running the tests, hence #25 which seems to indicate that model publisher already didn't work on 1.7 before this change, and 1.7 is required for this change. Which seems odd as we are using model publisher with 1.7, but anyway. I'm not sure I have the time right now to dig much further and fix unrelated 1.7 issues. We have worked around this issue in our project by sticking with an older version of model untils for now. Can you advise on the expected state of 1.7 compatibility? Is it supposed to work? Minor changes necessary? Have tests ever been run and passed for 1.7?
