### ISSUE TITLE
Project alive?

### ISSUE THREAD

**Issue by jedie** [jp74/django-model-publisher#29]
It seems that this project is not alive, isn't it?

**Comment by jedie** [comment]
Is https://github.com/andersinno/django-model-publisher-ai a better place?

**Comment by cdobbyn** [comment]
@jedie - I don't think it's alive. I got it back on it's feet in #28 a while back but it still needs work. It's pretty ugly. Doesn't seem jp74 is alive based on this:
https://github.com/jp74

**Comment by jedie** [comment]
I will use django-model-publisher-ai and IMHO it's a good idea to link to this fork. See #30

**Comment by jedie** [comment]
I used **django-model-publisher-ai** a while and create some pull requests. But the maintainer doesn't have the time to review and merge. So i now made another fork called **django-ya-model-publisher** merged my changes and release it on PyPi.

Links:

github: https://github.com/wearehoods/django-ya-model-publisher/
PyPi: https://pypi.org/project/django-ya-model-publisher/

**Comment by bashu** [comment]
@leesolway if you need help, you can share maintainers responsibility with me. I would be happy to support it.

**Comment by bashu** [comment]
@CptLemming thanks!

**Comment by bashu** [comment]
@cdobbyn @jedie alive!
