### ISSUE TITLE
upload on pypi.python.org 

### ISSUE THREAD

**Issue by bashu** [jp74/django-model-publisher#33]
Hey @leesolway, @jake74 

Can anyone upload new version (master branch) on pypi or grant me permission (nickname on pypi: bashu) to do it myself.

**Comment by bashu** [comment]
@CptLemming can you help with this?

**Comment by CptLemming** [comment]
Hey @bashu 
I've added you as a maintainer on PyPi, should be able to publish packages / updates there.

Thanks again for taking this on!

**Comment by bashu** [comment]
@jedie +1

**Comment by bashu** [comment]
@CptLemming I have uploaded "intermediate" release and now starting working on a next
