### ISSUE TITLE
How about django-mptt support ? 

### ISSUE THREAD

**Issue by skrzypek** [jp74/django-model-publisher#4]

**Comment by leesolway** [comment]
Thank you for the suggestion and sorry for the late reply. Currently we have no plans to implement support for MPTT however we would merge in a pull request.

**Comment by skrzypek** [comment]
I'm already rewrite this project for support mptt, but it's not finished yet https://github.com/skrzypek/django-mptt-model-publisher

but i'll drop it into `pip` as independent egg

**Comment by jedie** [comment]
Because this project is no longer maintained, I used: **django-model-publisher-ai** and have the question: about **treebeard** integration, see: https://github.com/andersinno/django-model-publisher-ai/issues/16

Maybe somebody's here interested in this.
